javac SQLEntityGenerator.java
jar cmf SQLEntityGenerator.mf SQLEntityGenerator.jar SQLEntityGenerator.class SQLEntityGenerator$SQLTable.class SQLEntityGenerator$SQLField.class SQLEntityGenerator.java
