# Command: commit
# Description: Generate commit message
# Category: session
# Version: 1
# Author: Yongjie

description = "Generate commit message"

prompt = """
Generate git commit message for current changes.

A good commit message may consist of a title and description, most commits should only have a title.
A good commit title should be short and informative, it may start with a verb, describing what was done and changed.

You shall not create the git commit yourself, just output the commit message, let the user decides.
"""
